### ISSUE TITLE
RealtimeDataCollector code

### ISSUE THREAD

**Issue by bloryo** [atcelen/BCI#1]
Hi Ata,

I'm currently doing a semester thesis on BCI at IIS and I was looking for your code for the PsychoPy-OpenViBE synchronization, but the folder "RealtimeDataCollector" is empty.
Could you upload the code?

Thanks!
Bettina

**Comment by atcelen** [comment]
Hello Bettina, Unfortunately I cannot share that Code on my own Github since I have also downloaded it from another Github page, but feel free to check it out : https://github.com/nemathahmed/OpenVibe-to-Python.git/ Sincerely,Ata Gesendet von Mail für Windows Von: Bettina LoryGesendet: Wednesday, 9 March 2022 18:23An: atcelen/BCICc: SubscribedBetreff: [atcelen/BCI] RealtimeDataCollector code (Issue #1) Hi Ata,I'm currently doing a semester thesis on BCI at IIS and I was looking for your code for the PsychoPy-OpenViBE synchronization, but the folder "RealtimeDataCollector" is empty.Could you upload the code?Thanks!Bettina—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by bloryo** [comment]
Great, Thank you for sharing!
Cheers,
Bettina

**Comment by atcelen** [comment]
Hello Bettina, Unfortunately I cannot share that Code on my own Github since I have also downloaded it from another Github page, but feel free to check it out : https://github.com/nemathahmed/OpenVibe-to-Python.git/ Sincerely,Ata Gesendet von Mail für Windows Von: Bettina LoryGesendet: Wednesday, 9 March 2022 18:23An: atcelen/BCICc: SubscribedBetreff: [atcelen/BCI] RealtimeDataCollector code (Issue #1) Hi Ata,I'm currently doing a semester thesis on BCI at IIS and I was looking for your code for the PsychoPy-OpenViBE synchronization, but the folder "RealtimeDataCollector" is empty.Could you upload the code?Thanks!Bettina—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
